language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dockeroffthebay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeroffthebay/docker-react npm run test  


